### ISSUE TITLE
Not able to see the snapshot embedded onto the report

### ISSUE THREAD

**Issue by salunkhe-ravi** [grasshopper7/cuke4-extent-screenshot#1]
Hi,

Firstly would like to thank you for putting up this project to sort out the snapshot issue with extent-cucumber-adapter4 version.

This has been an issue i've been struggling for like 3 days now.

So, I am now able to get snapshots in target-output but it doesnt embed onto the extentreport!.
My pom has:

<cucumber.version>4.8.0</cucumber.version>
<extent.adapter4.reports.version>1.0.8</extent.adapter4.reports.version>

(When i update the extent-cucmber-adapter4 version to latest v1.0.10 it gives me some freemarker error!)

I tried adding the @AfterStep what you had mentioned in your project in my hooks file as below:
	
@AfterStep(value = "@smoke")
public void afterSite(Scenario scenario) {
		System.out.println("AFTER SITE");

		if(scenario.isFailed()) {

			TakesScreenshot ts = (TakesScreenshot) DriverFactory.getDriver();
			byte[] screenshot = ts.getScreenshotAs(OutputType.BYTES);
			scenario.write("this is my failure message");
			scenario.embed(screenshot, "image/png", "Screenshot");
		}

	}

So again it now gives out the snapshots under test-output but its not "linking" or "embedding" into the extent html report.

Can you please help!.

**Comment by grasshopper7** [comment]
There is a workaround to use the logger or spark report. U can see the screenshots available in this repo. **Will try to look into the code for 1.0.8 and check it out.**
 From this issue it seems to be a path thing - https://github.com/extent-framework/extentreports-cucumber4-adapter/issues/20 in 1.0.10.
Strangely 1.0.9 and 1.0.10 both gives error which are an irritant.

**Comment by grasshopper7** [comment]
Have u looked at this PR - https://github.com/extent-framework/extentreports-cucumber4-adapter/issues/24

**Comment by grasshopper7** [comment]
Add line to private synchronized void handleEmbed(EmbedEvent event) in class ExtentCucumberAdapter 
**addTestStepScreenCaptureFromPath(url.getPath());**

after this line - stepTestThreadLocal.get().info("", MediaEntityBuilder.createScreenCaptureFromPath(f.getAbsolutePath()).build());

It works. U will need to import source for tag 1.0.8 and do the changes. Have not investigated further into this.
Check out the icon for the screenshots highlighted in red circles.

![Untitled](https://user-images.githubusercontent.com/10829355/77008461-32fcfd00-698c-11ea-83a1-c12461227813.png)

**Comment by salunkhe-ravi** [comment]
You are a genius grasshopper!
Thanks for spending time on this resolution.
Well how we proceed further now?....Will you be raising a PR with Anshoo?
Because this seems to be a major bug and will be affecting multiple users...
Also, should I take a source and make this fix? What do you suggest?
Thanks And Regards, Ravi Salunkhe.+91 9892 033 961https://www.linkedin.com/in/ravi-salunkhe-15485539/ 

    On Thursday, 19 March, 2020, 02:51:00 am IST, grasshopper <notifications@github.com> wrote:  
 
 


Add line to private synchronized void handleEmbed(EmbedEvent event) in class ExtentCucumberAdapter
addTestStepScreenCaptureFromPath(url.getPath());

after this line - stepTestThreadLocal.get().info("", MediaEntityBuilder.createScreenCaptureFromPath(f.getAbsolutePath()).build());

It works. U will need to import source for tag 1.0.8 and do the changes. Have not investigated further into this.
Check out the icon for the screenshots highlighted in red circles.

**Comment by grasshopper7** [comment]
This is at most a workaround. Seems like an issue with the freemaker template for extent-html report. Because the same code works for logger and spark report. You could investigate this further. 

Is the screenshot working in 1.0.10? U can try that version by setting logger report generation to false in configuration properties file which throws an error.

I think the artifact author is working on a fix. U could add the findings in the open issue - https://github.com/extent-framework/extentreports-cucumber4-adapter/issues/20. Or just go ahead and fix with a PR on latest version. 

For your project, you could make the changes in the source and install as a local maven jar till an official fix is available.

**Comment by salunkhe-ravi** [comment]
I'm getting this error!




Thanks And Regards, Ravi Salunkhe.+91 9892 033 961https://www.linkedin.com/in/ravi-salunkhe-15485539/ 

    On Thursday, 19 March, 2020, 02:51:00 am IST, grasshopper <notifications@github.com> wrote:  
 
 


Add line to private synchronized void handleEmbed(EmbedEvent event) in class ExtentCucumberAdapter
addTestStepScreenCaptureFromPath(url.getPath());

after this line - stepTestThreadLocal.get().info("", MediaEntityBuilder.createScreenCaptureFromPath(f.getAbsolutePath()).build());

It works. U will need to import source for tag 1.0.8 and do the changes. Have not investigated further into this.
Check out the icon for the screenshots highlighted in red circles.

**Comment by grasshopper7** [comment]
U missed out adding the error to the post. Which versions of adapter and cucumber?

**Comment by salunkhe-ravi** [comment]
Ok will mention the pom


Sent from Yahoo Mail for iPhone


On Friday, March 20, 2020, 8:32 AM, grasshopper <notifications@github.com> wrote:




U missed out adding the error to the post. Which versions of adapter and cucumber?

**Comment by salunkhe-ravi** [comment]
Seems to be resolved now!

https://github.com/extent-framework/extentreports-cucumber4-adapter/issues/20

**Comment by grasshopper7** [comment]
Cool will wait for official maven artifact to update post accordingly with 1.0.11 version

**Comment by salunkhe-ravi** [comment]
Can you please make the necessary changes to the repo and send out your Extentreport version which supports Cucumber v5?.
Or maybe do you have any plans for the same?
Thanks And Regards, Ravi Salunkhe.+91 9892 033 961https://www.linkedin.com/in/ravi-salunkhe-15485539/ 

    On Friday, 20 March, 2020, 06:07:10 pm IST, grasshopper <notifications@github.com> wrote:  
 
 


Cool will wait for official maven artifact to update post accordingly with 1.0.11 version

**Comment by grasshopper7** [comment]
Planning to upload it to maven under my groupid, hopefully by tomorrow. Had found some issues with it, fixing them

**Comment by salunkhe-ravi** [comment]
Cool!
Looking forward to it then as I would be upgrading my project to Cucumber v5.

And thanks for your blog!
Also, another thing, I’m more of a Java guy and if I have to ask like what other programming language one should learn next ?
This maybe be more like general purpose - web dev, test automation, mobile etc.!?

Sent from Yahoo Mail for iPhone


On Sunday, March 22, 2020, 2:27 PM, grasshopper <notifications@github.com> wrote:




Planning to upload it to maven under my groupid, hopefully by tomorrow. Had found some issues with it, fixing them

**Comment by grasshopper7** [comment]
This has been uploaded to nexus repo- https://oss.sonatype.org/#nexus-search;quick~tech.grasshopper. Should be synced with maven soon and available in tech.grasshopper maven groupid.
for web dev javascript esp frameworks is the way to go. test automation selenium plus python seems to be the goto combination.

**Comment by grasshopper7** [comment]
It is available at maven - https://search.maven.org/classic/#artifactdetails%7Ctech.grasshopper%7Cextentreports-cucumber5-adapter%7C1.0.0%7Cjar.

Maven search has yet to synch so not available diectly yet but hopefully soon.
